name: impact_app
description: A new Flutter project for Impact app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  fl_chart: ^0.71.0
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  permission_handler: ^11.0.0
  intl: ^0.18.0

  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1               # Tambahkan ini jika belum ada
  share_plus: ^7.2.1          # Tambahkan ini untuk fitur sharing

  # Firebase dependencies
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.10.7
  flutter_local_notifications: ^19.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png